name: "blog"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - selenium
    - minio

    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

    environment:
      - RAILS_ENV=development
      - LITESTREAM_INSTALL_DIR=/usr/local/bin
      - LITESTREAM_REPLICA_BUCKET=mybkt
      - LITESTREAM_REPLICA_ENDPOINT=http://minio:9000
      - LITESTREAM_ACCESS_KEY_ID=minioadmin
      - LITESTREAM_SECRET_ACCESS_KEY=minioadmin

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
      image: grafana/loki
      ports:
        - "3100:3100"
      volumes:
        - loki-data:/loki

  tempo:
    image: grafana/tempo
    ports:
      - "14268:14268"
      - "9411:9411"
    volumes:
      - tempo-data:/tmp/tempo

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  minio-data:
  grafana-data:
  loki-data:
  tempo-data:
