auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2024-09-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
  aws:
    access_key_id: minioadmin
    secret_access_key: minioadmin
    insecure: true
    endpoint: minio:9000
    s3forcepathstyle: true
    s3: s3://minioadmin:minioadmin@minio:9000/mybkt

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  per_stream_rate_limit: 10MB
  max_query_lookback: 672h # 28 days
  retention_period: 672h   # 28 days

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 500
      ttl: 24h

#compactor:
#  working_directory: /tmp/loki/compactor
#  compaction_interval: 24h

query_scheduler:
  # the TSDB index dispatches many more, but each individually smaller, requests.
  # We increase the pending request queue sizes to compensate.
  max_outstanding_requests_per_tenant: 32768

querier:
  # Each `querier` component process runs a number of parallel workers to process queries simultaneously.
  # You may want to adjust this up or down depending on your resource usage
  # (more available cpu and memory can tolerate higher values and vice versa),
  # but we find the most success running at around `16` with tsdb
  max_concurrent: 16